### ISSUE TITLE
Build wheels for pyreadstat 0.2.4

### ISSUE THREAD

**Issue by ofajardo** [MacPython/pyreadstat-wheels#1]
No tag yet for the version, will be set after all wheels have been built correctly.

**Comment by ofajardo** [comment]
succesfully built wheels and uploaded to pypi. Will release the tag after the deployment into conda is concluded.

**Comment by matthew-brett** [comment]
Nice - thanks.

**Comment by ofajardo** [comment]
Build failed for conda. Now trying the opposite approach, meaning first getting it to work on conda and then on wheels.

**Comment by ofajardo** [comment]
0.2.5 succeeded both in conda and wheels. Release made on pyreadstat repo. Done.
