### ISSUE TITLE
appveyor

### ISSUE THREAD

**Issue by ofajardo** [MacPython/pyreadstat-wheels#4]
hi @matthew-brett 

I have finally managed to build pyreadstat with mingw64 in appveyor. In summary the trick is to do it with m2w64-toolchain which is a conda package. It seems that's the way people is currently doing it. 

I have tested both independently and with your multibuild and seems to work:

see:

https://github.com/ofajardo/pyreadstat-wheels/blob/master/appveyor.yml

https://github.com/ofajardo/pyreadstat-wheels/commits/master

Do you think it is reasonable to integrate this in this repo so that I can produce the wheels for windows as well? Or do you see any drawback? I can always attach the appveyor directly to the main pyreadstat repo, that also should work but I like your approach better.

thanks

**Comment by matthew-brett** [comment]
I believe the main issue is that Python.org etc Python is built with MSVC, so file-handles and other runtime objects created inside Python, can reach the pyreadstat library, which uses the mingw-w64 runtime, and this can cause crashes, where the mingw-w64 tries to use a MSVC runtime object.  I don't know whether that's something that happens in practice though.

**Comment by ofajardo** [comment]
Yes, that's theoretically possible, however I have been building windows wheels manually with Mingw64 during one year now and there has been no issue report coming from this (I think).

What I want to change is doing it manually to doing it automatically with appveyor.

There is a couple of people who has proposed to adapt Readstat (the underlying C library) to work with MSVC. Changing the core code seems not that difficult but in addition autotools has to be replaced by Cmake and that seems to be a task that is preventing it from happening.

Until Readstat is ported to be compatible with MSVC I have no option but to stick with Mingw.

**Comment by matthew-brett** [comment]
Yes - sorry - I can't see any problem with automating it.

**Comment by ofajardo** [comment]
Thanks, then, if no objection I will adapt the appveyor.yml on this repo.

**Comment by ofajardo** [comment]
Appveyor is in good shape now. 

Any other comments from your side?

From my side, on travis I have privileges to cancel builds, re-run jobs, etc. May I get similar privileges on Appveyor?

**Comment by matthew-brett** [comment]
No comments from me - well done for getting it working.

For Appveyor - the builds are currently running on my account.  I'm happy to be corrected, but I don't think there's any way of me giving you access to the build machinery on my account.   The easiest thing would be if you started triggering builds from your account, and let me know, then I can stop doing the builds from my account.

**Comment by ofajardo** [comment]
It seems that on appveyor [team page](https://ci.appveyor.com/team) you could add me to the account. That however would grante me access to all your projects, so you would need to create a role that restricts the access to only pyreadstat-wheels project and add me to there, see this: https://help.appveyor.com/discussions/questions/569-allow-github-project-collaborator-to-configure-appveyor-project-configuration

IF this looks too convoluted (it kind of does to me) we do as you say. I tried to add this repo as a project on my appveyor account but didn't let me, I sent a access request to MacPython instead. If you grant that I guess I can add the project and I can take the process over from there.

**Comment by matthew-brett** [comment]
I think I did grant you access - did you work out how to proceed from
there?   If not, I'll look into the convoluted thing.

**Comment by ofajardo** [comment]
OK, now I went ahead adding pyreadstat-wheels github repo as an appveyor project. It says it will now send a request to you again to allow that. I guess this should be the last authorization? let's see ...
