### ISSUE TITLE
migrate travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by ofajardo** [MacPython/pyreadstat-wheels#5]
@matthew-brett this repo is still built in travis-ci.org. Today I tried to trigger a build and it doesn't work anymore (it doesn't appear in the travis-ci.org panel). I think that maybe it's because it should be migrated to the new travis-ci.com? Any other idea?
Could you please migrate the project to travis-ci.com? I cannot see this repo from my travis account.

thanks

**Comment by ofajardo** [comment]
@matthew-brett also if you prefer I don't bug you in the future I could build a new multibuild repo for myself so that I can do these things. Only thing I would need is a secure for rackspace. 

I also have another project https://github.com/ofajardo/pyreadr_wheels2 that would benefit from getting rackspace to deploy. Can I get it for that project please?

**Comment by matthew-brett** [comment]
Sorry - was distracted.  I haven't migrated the other repos, they still
seem to work on travis.org - but I can't tell you why - I haven't
investigated.

I'm afraid the Rackspace hosting is going away, if it has not already
gone.  Many projects are migrating to using anaconda.org instead - see

https://github.com/MacPython/scikit-learn-wheels/blob/master/azure/posix.yml#L135

Sorry - I haven't implemented that myself yet.

**Comment by ofajardo** [comment]
Thanks for the info!

It is repaired now - travis org and rackspace are still working.

The issue was the yaml had a line in matrix : exclude python 3.5 This for some reason was 
Making Travis to think there was nothing to build. What was the role of that exclude?

I made a new repo pyreadstat_wheels2 which is working but still needs to deploy to 
Anaconda cloud. Once that us ready I'll migrate there and this repo will become deprecated.
I will inform accordingly.

**Comment by matthew-brett** [comment]
The exclude was just because (I think) there were already several Python 3.5 builds in the matrix.  So no problem to remove the exclude.

**Comment by ofajardo** [comment]
Thanks. Just in case [here](https://github.com/ofajardo/pyreadstat_wheels2/blob/master/.travis.yml) the new repo with upload to Anaconda Cloud working. 

Setting the upload to anaconda was relatively easy (create an anaconda account and get a token, set the token in travis, set the commands in the yaml). The only interesting thing is that the anaconda-client from pypi is too old and was causing errors, so I had to install from github. The best seems to install with conda, but I was too lazy to set it up in travis, I am using it in appveyor tough.
