### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [MacPython/pyreadstat-wheels#6]
Problem
---------
On aarch64, ‘pip install pyreadstat’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi. 

Resolution
-----------
On aarch64, ‘pip install pyreadstat’ should download the wheels from pypi 

@Team Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by ofajardo** [comment]
hi @odidev, this repository is deprecated, the current one is here: https://github.com/ofajardo/pyreadstat_wheels3. 

If you are so kind, please submit your PR over there. 

thanks
