### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by mattip** [MacPython/pyreadstat-wheels#8]
Is pyreadstat still active? Many of the multibuild projects under this org have moved to cibuildwheel, and now build via CI jobs on the main repo. Can we archive this repo?

**Comment by ofajardo** [comment]
You can archive.

Pyreadstat is still active and I am still usung multibuild but on azure on a different repo.

**Comment by mattip** [comment]
Glad to hear the project is active. I will archive this, thanks.
